apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-flask-app
  template:
    metadata:
      labels:
        app: todo-flask-app
    spec:
      containers:
      - name: todo-flask-app
        image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/flask-app:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: ftodo-lask-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: todo-flask-app
