apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-app
  labels:
    app: todo-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-flask-app
  template:
    metadata:
      labels:
        app: todo-flask-app
    spec:
      containers:
      - name: todo-flask-app
        image: sushrutnet/todo-flask-app
        ports:
        - containerPort: 5000
